#!/bin/bash
# paxmmit V3
# Create message with proper reference to rep issue based on branch name ddd_issueName
# Then add all changes in unstaged and commit with the respective message
# Author: Rogério Júnior

if [ ! -z "$1" -a "$1" != " " ]; then

   declare number
   number=$(git branch | grep '*' | sed 's/.*\([0-9]\{3\}\).*/\1/') 

   if [ $number -eq $number 2> /dev/null ]; then
      number=number
   else
      echo -e "@@@@@@@@@@@@@@@@@@@@@@@@@@@ W A R N I N G @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"  
      echo -e "\nYou're out of a issue branch, the only way of contibuiting to Pax Org! :X "
      echo -e "\nAre you absolutely certain to try to commit in $(git branch | grep '*' | sed 's|[*]||g') ? (it maybe be refused on Github)\n"

      read -p "(y/n) " flag

      if [ $flag == "n" ]; then
         exit 1
      fi

      echo ""
      read -p "What's the issue number? " number
      echo ""
   fi

   message="pax-app/Wiki#$number $1"

   echo -e ""
   read -p "Are you pairing? (y/n) " pairing
   echo ""

   if [ $pairing != "n" ]; then

      declare -A map

      map["a"]="Co-authored-by: Gabriel Albino <enggabrielalbino@gmail.com>"
      map["d"]="Co-authored-by: Lucas Dutra <ldutra98@gmail.com>"
      map["e"]="Co-authored-by: Esio Freitas <esio.gustavo@gmail.com>"
      map["fa"]="Co-authored-by: Fabiana Ribas <fabianalv.ribas@gmail.com>"
      map["fe"]="Co-authored-by: Felipe Campos <fepas.unb@gmail.com>"
      map["k"]="Co-authored-by: Kaique Borges <rique.kaique@gmail.com>"
      map["mar"]="Co-authored-by: Marcos Nery <marcosnery.comp@gmail.com>"
      map["mat"]="Co-authored-by: Matheus Pimenta <ultra10vascaino@gmail.com>"
      map["r"]="Co-authored-by: Rogério Júnior <junior.rogerio8@gmail.com>"
      map["y"]="Co-authored-by: Youssef Muhamad <emaildeyoussefmuhamad@gmail.com>"

      declare flag="y"

      message+="\n"

      while [ $flag != 'n' ]; do
         echo -e "With who?\n"
         read -p "(a)lbino/(d)utra/(e)sio/(fa)bi/(fe)pas/(k)aique/(mar)cos/(mat)heus/(r)oger/(y)oussef " pairing_name
         echo ""

         message+="\n${map[${pairing_name}]}"

         read -p "Anyone else? (y/n) " flag
         echo ""
      done

   fi

   echo -e "That's the correct message ?\n\n\n$message\n\n"
   read -p "(y/n): " flag

   if [ $flag != 'n' ]; then
      echo ""

      read -p "What do you want do stage? (e)verything/(s)omethings/(n)othing " flag

      echo ""

      if [ $flag == 'e' ]; then
         git add .
      else 
         if [ $flag == 's' ]; then
            echo -e "Let's stage the changes!\n\n"
            git add -i

            echo ""
         fi
      fi

      git commit -m"$(echo -e $message)"
      echo -e "\n\n"
      echo -e "Everything commited!! ;)"
   else
      echo -e "\n\n"
      echo "Run me again! :("
   fi
else
   echo -e "Wheres the message?! Run me again"
fi